In [1]:
import pandas as pd
fandango = pd.read_csv("fandango-score-comparison.csv")

In [2]:
last = fandango.shape[0]-1

In [3]:
first_last = fandango.iloc[[0, last]]

In [4]:
first_last

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.30,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

## Use personalized index

* Utiliser la methode set_index pour  indexer  notre DataFrame fandango avec la colonne "Film". A preciser
    que nous souhaitons conserver la colonne "FILM". De plus nous souhaitons garder le DataFrame d'origine et en creer un
    nouveau que nous assignerons à la variable fandango_films.
* Afficher l'index du DataFrame fandango_films à l'aide de l'attribut index.

In [5]:
fandango_films = fandango.set_index(fandango["FILM"], inplace=False, drop=False)

In [6]:
fandango_films.index

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

## Select values from a personalized index

* Selectionner les films suivants depuis le DataFrame  fandango_films (dans l'ordre suivant) et assigner les à la variable
    some_movies:
    
        * "Top Five (2014)"
        * "Black Sea (2015)"
        * "Taken 3 (2015)"
* Afficher le resultat.

In [7]:
some_movies = fandango_films.loc[["Top Five (2014)", "Black Sea (2015)", "Taken 3 (2015)"]]

In [8]:
some_movies

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Top Five (2014),Top Five (2014),86,64,81,6.8,6.5,4.0,3.5,4.30,3.2,...,3.25,4.5,3.0,4.0,3.5,3.5,124,16876,3223,0.5
Black Sea (2015),Black Sea (2015),82,60,62,6.6,6.4,4.0,3.5,4.10,3.0,...,3.20,4.0,3.0,3.0,3.5,3.0,37,16547,218,0.5
Taken 3 (2015),Taken 3 (2015),9,46,26,4.6,6.1,4.5,4.1,0.45,2.3,...,3.05,0.5,2.5,1.5,2.5,3.0,240,104235,6757,0.4

## Method Apply() on DataFrame column

* Obtenir le dataframe float_df que j'ai realisé en exemple (qui retourne les colonnes decimale float64)
* Utilisez la methode Apply() sur ce dataframe float_df afin de diviser par 2 chaque valeur et assigner le resultat a la variable exo_df
* Affichez les premiere ligne du resultat

In [14]:
import numpy as np
types = fandango_films.dtypes
float_df = fandango_films[types[types.values == "float64"].index]
exo_df = float_df.apply(lambda x : np.divide(x, 2))

In [15]:
print(exo_df)

                                           Metacritic_User  IMDB  \
FILM
Avengers: Age of Ultron (2015)                        3.55  3.90
Cinderella (2015)                                     3.75  3.55
Ant-Man (2015)                                        4.05  3.90
Do You Believe? (2015)                                2.35  2.70
Hot Tub Time Machine 2 (2015)                         1.70  2.55
...                                                    ...   ...
Mr. Holmes (2015)                                     3.95  3.70
'71 (2015)                                            3.75  3.60
Two Days, One Night (2014)                            4.40  3.70
Gett: The Trial of Viviane Amsalem (2015)             3.65  3.90
Kumiko, The Treasure Hunter (2015)                    3.20  3.35

                                           Fandango_Stars  \
FILM
Avengers: Age of Ultron (2015)                       2.50
Cinderella (2015)                                    2.50
Ant-Man (2015)                                       2.50
Do You Believe? (2015)                               2.50
Hot Tub Time Machine 2 (2015)                        1.75
...                                                   ...
Mr. Holmes (2015)                                    2.00
'71 (2015)                                           1.75
Two Days, One Night (2014)                           1.75
Gett: The Trial of Viviane Amsalem (2015)            1.75
Kumiko, The Treasure Hunter (2015)                   1.75

                                           Fandango_Ratingvalue  RT_norm  \
FILM
Avengers: Age of Ultron (2015)                             2.25    1.850
Cinderella (2015)                                          2.25    2.125
Ant-Man (2015)                                             2.25    2.000
Do You Believe? (2015)                                     2.25    0.450
Hot Tub Time Machine 2 (2015)                              1.50    0.350
...                                                         ...      ...
Mr. Holmes (2015)                                          2.00    2.175
'71 (2015)                                                 1.75    2.425
Two Days, One Night (2014)                                 1.75    2.425
Gett: The Trial of Viviane Amsalem (2015)                  1.75    2.500
Kumiko, The Treasure Hunter (2015)                         1.75    2.175

                                           RT_user_norm  Metacritic_norm  \
FILM
Avengers: Age of Ultron (2015)                    2.150            1.650
Cinderella (2015)                                 2.000            1.675
Ant-Man (2015)                                    2.250            1.600
Do You Believe? (2015)                            2.100            0.550
Hot Tub Time Machine 2 (2015)                     0.700            0.725
...                                                 ...              ...
Mr. Holmes (2015)                                 1.950            1.675
'71 (2015)                                        2.050            2.075
Two Days, One Night (2014)                        1.950            2.225
Gett: The Trial of Viviane Amsalem (2015)         2.025            2.250
Kumiko, The Treasure Hunter (2015)                1.575            1.700

                                           Metacritic_user_nom  IMDB_norm  \
FILM
Avengers: Age of Ultron (2015)                           1.775      1.950
Cinderella (2015)                                        1.875      1.775
Ant-Man (2015)                                           2.025      1.950
Do You Believe? (2015)                                   1.175      1.350
Hot Tub Time Machine 2 (2015)                            0.850      1.275
...                                                        ...        ...
Mr. Holmes (2015)                                        1.975      1.850
'71 (2015)                                               1.875      1.800
Two Days, One Night (2014)                               2.200      1.850
Gett: The Trial of Viviane Amsalem (2015)                1.825      1.950
Kumiko, The Treasure Hunter (2015)                       1.600      1.675

                                           RT_norm_round  RT_user_norm_round  \
FILM
Avengers: Age of Ultron (2015)                      1.75                2.25
Cinderella (2015)                                   2.25                2.00
Ant-Man (2015)                                      2.00                2.25
Do You Believe? (2015)                              0.50                2.00
Hot Tub Time Machine 2 (2015)                       0.25                0.75
...                                                  ...                 ...
Mr. Holmes (2015)                                   2.25                2.00
'71 (2015)                                          2.50                2.00
Two Days, One Night (2014)                          2.50                2.00
Gett: The Trial of Viviane Amsalem (2015)           2.50                2.00
Kumiko, The Treasure Hunter (2015)                  2.25                1.50

                                           Metacritic_norm_round  \
FILM
Avengers: Age of Ultron (2015)                              1.75
Cinderella (2015)                                           1.75
Ant-Man (2015)                                              1.50
Do You Believe? (2015)                                      0.50
Hot Tub Time Machine 2 (2015)                               0.75
...                                                          ...
Mr. Holmes (2015)                                           1.75
'71 (2015)                                                  2.00
Two Days, One Night (2014)                                  2.25
Gett: The Trial of Viviane Amsalem (2015)                   2.25
Kumiko, The Treasure Hunter (2015)                          1.75

                                           Metacritic_user_norm_round  \
FILM
Avengers: Age of Ultron (2015)                                   1.75
Cinderella (2015)                                                2.00
Ant-Man (2015)                                                   2.00
Do You Believe? (2015)                                           1.25
Hot Tub Time Machine 2 (2015)                                    0.75
...                                                               ...
Mr. Holmes (2015)                                                2.00
'71 (2015)                                                       2.00
Two Days, One Night (2014)                                       2.25
Gett: The Trial of Viviane Amsalem (2015)                        1.75
Kumiko, The Treasure Hunter (2015)                               1.50

                                           IMDB_norm_round  \
FILM
Avengers: Age of Ultron (2015)                        2.00
Cinderella (2015)                                     1.75
Ant-Man (2015)                                        2.00
Do You Believe? (2015)                                1.25
Hot Tub Time Machine 2 (2015)                         1.25
...                                                    ...
Mr. Holmes (2015)                                     1.75
'71 (2015)                                            1.75
Two Days, One Night (2014)                            1.75
Gett: The Trial of Viviane Amsalem (2015)             2.00
Kumiko, The Treasure Hunter (2015)                    1.75

                                           Fandango_Difference
FILM
Avengers: Age of Ultron (2015)                            0.25
Cinderella (2015)                                         0.25
Ant-Man (2015)                                            0.25
Do You Believe? (2015)                                    0.25
Hot Tub Time Machine 2 (2015)                             0.25
...                                                        ...
Mr. Holmes (2015)                                         0.00
'71 (2015)                                                0.00
Two Days, One Night (2014)                                0.00
Gett: The Trial of Viviane Amsalem (2015)                 0.00
Kumiko, The Treasure Hunter (2015)                        0.00

[146 rows x 15 columns]

## Method Apply() on DataFrame Row

* Utiliser la methode apply pour calculer la moyenne (methode mean() de la librairie Numpy) des valeurs de chaque film  pour 'RT_user_norm' et 'metacritic_user' puis assigner le résultat à la variable rt_mt_means.
* Afficher 5 premieres valeur de rt_mt_means.

In [19]:
rt_mt_means = float_df[["RT_user_norm", "Metacritic_user_nom"]]
rt_mt_means.apply(lambda x : np.mean(x), axis = 1)

FILM
Avengers: Age of Ultron (2015)               3.925
Cinderella (2015)                            3.875
Ant-Man (2015)                               4.275
Do You Believe? (2015)                       3.275
Hot Tub Time Machine 2 (2015)                1.550
                                             ...
Mr. Holmes (2015)                            3.925
'71 (2015)                                   3.925
Two Days, One Night (2014)                   4.150
Gett: The Trial of Viviane Amsalem (2015)    3.850
Kumiko, The Treasure Hunter (2015)           3.175
Length: 146, dtype: float64